# Generated by Django 5.2.3 on 2025-06-25 05:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0005_alter_cookingdiary_ai_summary_and_more'),
        ('users', '0003_couple_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoupleMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('summary', models.TextField(blank=True)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('entries_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couple_memories', to='users.couple')),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='MemoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('mood', models.CharField(choices=[('happy', '😊 Happy'), ('proud', '😎 Proud'), ('fail', '😖 Fail')], default='happy', max_length=8)),
                ('ai_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='couplememory.couplememory')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.recipe')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemoryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='couplememory.memoryentry')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='couplememory',
            name='winner_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_week', to='couplememory.memoryentry'),
        ),
        migrations.CreateModel(
            name='MemoryMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='memories/media/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='couplememory.memoryentry')),
            ],
        ),
        migrations.AddIndex(
            model_name='memoryentry',
            index=models.Index(fields=['memory', 'created_at'], name='couplememor_memory__fa72dc_idx'),
        ),
        migrations.AddIndex(
            model_name='couplememory',
            index=models.Index(fields=['couple', 'week_start'], name='couplememor_couple__5b9ddc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='couplememory',
            unique_together={('couple', 'week_start')},
        ),
    ]
