# Generated by Django 5.2.3 on 2025-06-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couplememory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorymedia',
            name='is_highlight',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
