# Generated by Django 5.2.3 on 2025-06-30 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couplememory', '0002_memorymedia_is_highlight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memorymedia',
            options={'ordering': ['-created_at']},
        ),
    ]
