# Generated by Django 5.2.3 on 2025-07-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couplememory', '0003_alter_memorymedia_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoryentry',
            name='mood',
            field=models.CharField(choices=[('nailed', '🏆 Nailed'), ('grind', '🛠 Grinding'), ('love', '💖 Loved'), ('lucky', '🎲 Lucky'), ('chaos', '🔥 Chaos')], default='nailed', max_length=8),
        ),
    ]
