# Generated by Django 5.2.3 on 2025-08-20 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couplememory', '0004_alter_memoryentry_mood'),
        ('users', '0003_couple_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='couplememory',
            options={'ordering': ['-round_start']},
        ),
        migrations.RemoveIndex(
            model_name='couplememory',
            name='couplememor_couple__5b9ddc_idx',
        ),
        migrations.RenameField(
            model_name='couplememory',
            old_name='week_end',
            new_name='round_end',
        ),
        migrations.RenameField(
            model_name='couplememory',
            old_name='week_start',
            new_name='round_start',
        ),
        migrations.AlterUniqueTogether(
            name='couplememory',
            unique_together={('couple', 'round_start')},
        ),
        migrations.AlterField(
            model_name='couplememory',
            name='winner_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_round', to='couplememory.memoryentry'),
        ),
        migrations.AddIndex(
            model_name='couplememory',
            index=models.Index(fields=['couple', 'round_start'], name='couplememor_couple__3882de_idx'),
        ),
    ]
