# Generated by Django 5.2.5 on 2025-08-23 00:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couplememory', '0004_alter_memoryentry_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoryentry',
            name='ai_score',
            field=models.FloatField(blank=True, help_text='backwards-compatible score, preferring AIJudgment.overall_score', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.CreateModel(
            name='AIJudgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(help_text='AI总体评分 (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('visual_appeal', models.FloatField(help_text='视觉呈现与摆盘 (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cooking_technique', models.FloatField(help_text='烹饪技巧与火候 (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ingredient_freshness', models.FloatField(help_text='食材新鲜度与搭配 (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ai_comment', models.TextField(help_text='AI详细评语')),
                ('ai_summary', models.CharField(help_text='AI简短总结', max_length=200)),
                ('confidence', models.FloatField(default=0.8, help_text='AI评分置信度 (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('model_version', models.CharField(default='gpt-4o-mini', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_judgment', to='couplememory.memoryentry')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entry', 'created_at'], name='couplememor_entry_i_20c823_idx')],
            },
        ),
    ]
