# Generated by Django 5.2.5 on 2025-08-24 03:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couplememory', '0006_aijudgment_battle_comment_aijudgment_battle_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aijudgment',
            name='ai_comment',
            field=models.TextField(default='', help_text='AI detailed feedback (legacy compatibility)'),
        ),
        migrations.AlterField(
            model_name='aijudgment',
            name='ai_summary',
            field=models.CharField(default='', help_text='AI brief summary (legacy compatibility)', max_length=200),
        ),
        migrations.AlterField(
            model_name='aijudgment',
            name='battle_comment',
            field=models.TextField(blank=True, default='', help_text='Couple battle AI feedback'),
        ),
        migrations.AlterField(
            model_name='aijudgment',
            name='battle_result',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed battle result data', null=True),
        ),
        migrations.AlterField(
            model_name='aijudgment',
            name='battle_summary',
            field=models.CharField(blank=True, default='', help_text='Couple battle AI summary', max_length=200),
        ),
        migrations.AlterField(
            model_name='aijudgment',
            name='confidence',
            field=models.FloatField(default=0.8, help_text='AI scoring confidence (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='aijudgment',
            name='cooking_technique',
            field=models.FloatField(help_text='Cooking technique and execution (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='aijudgment',
            name='individual_comment',
            field=models.TextField(default='', help_text='Individual dish AI detailed feedback'),
        ),
        migrations.AlterField(
            model_name='aijudgment',
            name='individual_summary',
            field=models.CharField(default='', help_text='Individual dish AI brief summary', max_length=200),
        ),
        migrations.AlterField(
            model_name='aijudgment',
            name='ingredient_freshness',
            field=models.FloatField(help_text='Ingredient freshness and pairing (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='aijudgment',
            name='overall_score',
            field=models.FloatField(help_text='AI overall score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='aijudgment',
            name='visual_appeal',
            field=models.FloatField(help_text='Visual presentation and plating (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='memoryentry',
            name='ai_score',
            field=models.FloatField(blank=True, help_text='Legacy AI score - prefer AIJudgment.overall_score', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
