# Generated by Django 5.2.3 on 2025-08-24 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couplememory', '0005_alter_couplememory_options_and_more'),
        ('couplememory', '0007_alter_aijudgment_ai_comment_and_more'),
    ]

    operations = [
    ]
