# Generated by Django 5.2.5 on 2025-08-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couplememory', '0008_merge_20250824_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aijudgment',
            name='model_version',
            field=models.CharField(default='gpt-5', max_length=50),
        ),
    ]
