# Generated by Django 5.2.3 on 2025-06-21 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template identifier", max_length=100, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of when to use this template"
                    ),
                ),
                (
                    "template",
                    models.TextField(
                        help_text="Message template with {variable} placeholders"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sms_templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OTPRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Original phone number provided", max_length=50
                    ),
                ),
                (
                    "formatted_phone",
                    models.CharField(
                        help_text="Formatted phone number used for sending",
                        max_length=20,
                    ),
                ),
                (
                    "otp_id",
                    models.CharField(
                        help_text="OTP ID returned by Textbelt",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        default="verification",
                        help_text="Purpose of OTP (e.g., login, registration, password_reset)",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("expired", "Expired"),
                            ("failed", "Failed"),
                            ("max_attempts", "Max Attempts Exceeded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "attempts",
                    models.IntegerField(
                        default=0, help_text="Number of verification attempts"
                    ),
                ),
                (
                    "generation_response",
                    models.JSONField(
                        blank=True, help_text="Response from OTP generation", null=True
                    ),
                ),
                (
                    "verification_responses",
                    models.JSONField(
                        default=list, help_text="List of verification attempt responses"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the request", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="User agent of the request", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(help_text="OTP expiration time")),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when OTP was successfully verified",
                        null=True,
                    ),
                ),
                (
                    "last_attempt_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of last verification attempt",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who requested the OTP",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="otp_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "otp_records",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["otp_id"], name="otp_records_otp_id_9b3bec_idx"
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="otp_records_user_id_66f2c1_idx",
                    ),
                    models.Index(
                        fields=["phone_number", "-created_at"],
                        name="otp_records_phone_n_c27004_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="otp_records_status_d66979_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="otp_records_expires_b98a7e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SMSRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Original phone number provided", max_length=50
                    ),
                ),
                (
                    "formatted_phone",
                    models.CharField(
                        help_text="Formatted phone number used for sending",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(help_text="SMS message content")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if sending failed",
                        null=True,
                    ),
                ),
                (
                    "textbelt_response",
                    models.JSONField(
                        blank=True,
                        help_text="Raw response from Textbelt API",
                        null=True,
                    ),
                ),
                ("attempts", models.IntegerField(default=1)),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the request", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="User agent of the request", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when SMS was successfully sent",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered the SMS",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sms_records",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="sms_records_user_id_98c25f_idx",
                    ),
                    models.Index(
                        fields=["phone_number", "-created_at"],
                        name="sms_records_phone_n_778398_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="sms_records_status_415221_idx",
                    ),
                ],
            },
        ),
    ]
