# Generated by Django 5.2.3 on 2025-06-21 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_service", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="otprecord",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who requested the OTP",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sms_otp_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
