# Generated by Django 5.2.3 on 2025-06-21 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms_service", "0002_alter_otprecord_user"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="otprecord",
            new_name="sms_otp_rec_otp_id_a8f5c6_idx",
            old_name="otp_records_otp_id_9b3bec_idx",
        ),
        migrations.RenameIndex(
            model_name="otprecord",
            new_name="sms_otp_rec_user_id_67dde3_idx",
            old_name="otp_records_user_id_66f2c1_idx",
        ),
        migrations.RenameIndex(
            model_name="otprecord",
            new_name="sms_otp_rec_phone_n_523bec_idx",
            old_name="otp_records_phone_n_c27004_idx",
        ),
        migrations.RenameIndex(
            model_name="otprecord",
            new_name="sms_otp_rec_status_cd74eb_idx",
            old_name="otp_records_status_d66979_idx",
        ),
        migrations.RenameIndex(
            model_name="otprecord",
            new_name="sms_otp_rec_expires_2e913d_idx",
            old_name="otp_records_expires_b98a7e_idx",
        ),
        migrations.AlterModelTable(
            name="otprecord",
            table="sms_otp_records",
        ),
    ]
