# Generated by Django 5.2.3 on 2025-06-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sms_service",
            "0003_rename_otp_records_otp_id_9b3bec_idx_sms_otp_rec_otp_id_a8f5c6_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="otprecord",
            name="otp_id",
            field=models.CharField(
                help_text="Unique user ID for this OTP session (used for verification)",
                max_length=100,
                unique=True,
            ),
        ),
    ]
