# Generated by Django 5.2.3 on 2025-06-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_service", "0004_alter_otprecord_otp_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkSMSProxy",
            fields=[],
            options={
                "verbose_name": "Bulk SMS",
                "verbose_name_plural": "Bulk SMS",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("sms_service.smsrecord",),
        ),
        migrations.AddField(
            model_name="smsrecord",
            name="is_read",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user has read/acknowledged this SMS notification",
            ),
        ),
    ]
