# Generated by Django 5.2.3 on 2025-06-14 09:08

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=users.models.generate_couple_code, help_text='Invite code for partner', max_length=8, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Couple',
                'verbose_name_plural': 'Couples',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoupleMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Couple Membership',
                'verbose_name_plural': 'Couple Memberships',
            },
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['username']},
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_opt_in',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sms_opt_in',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='user_email_idx'),
        ),
        migrations.AddField(
            model_name='couplemembership',
            name='couple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.couple'),
        ),
        migrations.AddField(
            model_name='couplemembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='couple',
            name='members',
            field=models.ManyToManyField(related_name='couples', through='users.CoupleMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='couplemembership',
            index=models.Index(fields=['couple', 'user'], name='cm_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='couplemembership',
            unique_together={('couple', 'user')},
        ),
        migrations.AddIndex(
            model_name='couple',
            index=models.Index(fields=['code'], name='couple_code_idx'),
        ),
    ]
