# Generated by Django 5.2.3 on 2025-06-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_couple_couplemembership_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='couple',
            name='name',
            field=models.CharField(blank=True, help_text="Optional display name shown in UI (e.g. 'Alice & Bob')", max_length=100, null=True),
        ),
    ]
