# Generated by Django 5.2.3 on 2025-06-28 22:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0003_couple_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("score", "Score"),
                            ("compare", "Compare"),
                            ("detect", "Detect Ingredients"),
                        ],
                        db_index=True,
                        help_text="Type of prompt operation",
                        max_length=12,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique identifier for this prompt template",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "template",
                    models.TextField(
                        help_text="Prompt template; use Python str.format placeholders"
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        default="gpt-4o-mini",
                        help_text="Default LLM model to use",
                        max_length=50,
                        verbose_name="Model",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Designates whether this prompt is active",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Prompt",
                "verbose_name_plural": "AI Prompts",
                "ordering": ["kind", "name"],
                "indexes": [
                    models.Index(fields=["kind"], name="idx_ai_prompt_kind"),
                    models.Index(fields=["is_active"], name="idx_ai_prompt_active"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AIRequestLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this log entry",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "prompt_name",
                    models.CharField(
                        blank=True,
                        help_text="Snapshot of prompt.name at log time",
                        max_length=50,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        db_index=True,
                        help_text="Category of the request",
                        max_length=12,
                    ),
                ),
                (
                    "request_payload",
                    models.JSONField(
                        blank=True, help_text="Full payload sent to the LLM", null=True
                    ),
                ),
                (
                    "response",
                    models.JSONField(
                        blank=True,
                        help_text="Raw JSON response from the LLM",
                        null=True,
                    ),
                ),
                (
                    "latency",
                    models.FloatField(
                        default=0.0, help_text="Round-trip latency in seconds"
                    ),
                ),
                (
                    "couple",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated couple, if applicable",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.couple",
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reference to the used prompt template",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="cookai.aiprompt",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered the request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Request Log",
                "verbose_name_plural": "AI Request Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["kind"], name="idx_ai_log_kind"),
                    models.Index(fields=["created_at"], name="idx_ai_log_created"),
                ],
            },
        ),
    ]
