# Generated by Django 5.2.3 on 2025-07-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprompt',
            name='model_name',
            field=models.CharField(default='o4-mini', help_text='Default LLM model to use', max_length=50, verbose_name='Model'),
        ),
    ]
