# Generated by Django 5.2.5 on 2025-08-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookai', '0002_alter_aiprompt_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprompt',
            name='model_name',
            field=models.CharField(default='gpt-5', help_text='Default LLM model to use', max_length=50, verbose_name='Model'),
        ),
    ]
