# Generated by Django 5.2.3 on 2025-10-22 06:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookai', '0003_alter_aiprompt_model_name'),
        ('couplememory', '0009_alter_aijudgment_model_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIScoreLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='日志唯一标识', primary_key=True, serialize=False)),
                ('image_urls', models.JSONField(default=list, help_text='原始图片 URL 列表 ["http://..."]')),
                ('image_base64_data', models.TextField(blank=True, help_text='Base64 encoded image data for the OpenAI API')),
                ('recipe_context', models.JSONField(default=dict, help_text='Recipe context: {name, instructions, ingredients}')),
                ('full_prompt', models.TextField(help_text='the full prompt sent to OpenAI, tier system included')),
                ('model_name', models.CharField(default='gpt-5', help_text='使用的模型名称', max_length=50)),
                ('api_request_params', models.JSONField(default=dict, help_text='the complete OpenAI API request parameters')),
                ('api_response', models.JSONField(blank=True, help_text='OpenAI API 原始响应', null=True)),
                ('parsed_score', models.JSONField(blank=True, help_text='解析后的评分结果 {overall_score, visual_appeal, ...}', null=True)),
                ('latency', models.FloatField(default=0.0, help_text='API 响应延迟（秒）')),
                ('token_count', models.IntegerField(default=0, help_text='估算的 token 数量')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('success', '成功'), ('failed', '失败'), ('timeout', '超时')], db_index=True, default='pending', help_text='请求状态', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='错误信息（如果失败）')),
                ('ai_judgment', models.ForeignKey(blank=True, help_text='the related AIJudgment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_logs', to='couplememory.aijudgment')),
                ('memory_entry', models.ForeignKey(blank=True, help_text='the related MemoryEntry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_score_logs', to='couplememory.memoryentry')),
            ],
            options={
                'verbose_name': 'AI 评分日志',
                'verbose_name_plural': 'AI 评分日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='idx_ai_score_status'), models.Index(fields=['created_at'], name='idx_ai_score_created'), models.Index(fields=['model_name'], name='idx_ai_score_model')],
            },
        ),
    ]
