# Generated by Django 5.2.3 on 2025-10-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_pet_prompt_display_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfig',
            name='enable_reward_cooldown',
            field=models.BooleanField(default=False, help_text='Enable reward cooldown. When disabled, players can claim infinitely (dev-friendly).'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='reward_cooldown_hours',
            field=models.PositiveIntegerField(default=2, help_text='Cooldown duration in hours. Only effective when enable_reward_cooldown=True.'),
        ),
    ]
