# Generated by Django 5.2.3 on 2025-10-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_alter_systemconfig_enable_reward_cooldown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='nice_guy_score_floor',
            field=models.PositiveIntegerField(default=60, help_text='floor applied in encouraging mode. Range: 50-80。defaults to 60, so nobody is scored too harshly.'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='nice_guy_upscale_base',
            field=models.PositiveIntegerField(default=80, help_text='starting score for the encouraging upscale. Range: 70-90。defaults to 80, mapping 0-100 onto 80-100.'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='nice_guy_upscale_range',
            field=models.PositiveIntegerField(default=20, help_text='score span for the encouraging upscale. Range: 10-30。defaults to 20, so the upscale band is[base, base+range]。'),
        ),
    ]
