# Generated by Django 5.2.3 on 2025-06-15 20:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_couple_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('slug', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=120)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('couples', models.ManyToManyField(blank=True, related_name='badges', to='users.couple')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(choices=[('panda', 'Panda'), ('cat', 'Cat'), ('dog', 'Dog')], default='panda', max_length=20)),
                ('nickname', models.CharField(default='Kinza', max_length=30)),
                ('level', models.PositiveIntegerField(default=1)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('next_lv_xp', models.PositiveIntegerField(default=10)),
                ('skin', models.CharField(default='default', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couple', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pet', to='users.couple')),
            ],
        ),
        migrations.CreateModel(
            name='PetStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hunger', models.PositiveSmallIntegerField(default=100)),
                ('happiness', models.PositiveSmallIntegerField(default=100)),
                ('hygiene', models.PositiveSmallIntegerField(default=100)),
                ('last_tick', models.DateField(default=django.utils.timezone.now)),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='petcare.pet')),
            ],
        ),
        migrations.CreateModel(
            name='SurpriseBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('mission', 'Mission'), ('streak', 'Streak')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('reward', models.JSONField(blank=True, null=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='users.couple')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('cook', 'Cook'), ('photo', 'Photo'), ('compliment', 'Compliment'), ('ai', 'AI Bonus')], max_length=12)),
                ('points', models.PositiveIntegerField()),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='users.couple')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['couple', 'created_at'], name='petcare_act_couple__3c5813_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeeklyMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('description', models.CharField(max_length=120)),
                ('target_cnt', models.PositiveSmallIntegerField(default=1)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('reward_pts', models.PositiveSmallIntegerField(default=5)),
                ('is_done', models.BooleanField(default=False)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='users.couple')),
            ],
            options={
                'unique_together': {('couple', 'week_start')},
            },
        ),
    ]
