# Generated by Django 5.2.3 on 2025-06-15 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0001_initial'),
        ('recipes', '0001_initial'),
        ('users', '0003_couple_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('C', 'Custom')], default='W', max_length=1)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('description', models.CharField(default='Cook any veggie dish together 🥗', max_length=160)),
                ('target_kind', models.CharField(default='cook', max_length=12)),
                ('target_cnt', models.PositiveIntegerField(default=1)),
                ('reward_pts', models.PositiveIntegerField(default=5)),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PetMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('tips', 'Tip'), ('summary', 'Weekly Summary'), ('recommend', 'Menu Recommend')], default='tips', max_length=12)),
                ('content', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_fire', models.DateTimeField()),
                ('template', models.CharField(default='Time to cook & feed your pet!', max_length=140)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReminderRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.PositiveSmallIntegerField(default=19)),
                ('minute', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RewardBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('mission', 'Mission'), ('streak', 'Streak'), ('admin', 'Admin')], max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='surprisebox',
            name='couple',
        ),
        migrations.AlterUniqueTogether(
            name='weeklymission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='weeklymission',
            name='couple',
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveIndex(
            model_name='activity',
            name='petcare_act_couple__3c5813_idx',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='payload',
            new_name='metadata',
        ),
        migrations.RenameField(
            model_name='badge',
            old_name='awarded_at',
            new_name='added',
        ),
        migrations.RenameField(
            model_name='badge',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='next_lv_xp',
            new_name='next_level',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.AddField(
            model_name='activity',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.recipeingredienttask'),
        ),
        migrations.AddField(
            model_name='activity',
            name='streak',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['couple', 'kind', 'created'], name='petcare_act_couple__906751_idx'),
        ),
        migrations.AddField(
            model_name='mission',
            name='couple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='users.couple'),
        ),
        migrations.AddField(
            model_name='petmessage',
            name='couple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_messages', to='users.couple'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='couple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='users.couple'),
        ),
        migrations.AddField(
            model_name='reminderrule',
            name='couple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_rules', to='users.couple'),
        ),
        migrations.AddField(
            model_name='rewardbox',
            name='couple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='users.couple'),
        ),
        migrations.DeleteModel(
            name='SurpriseBox',
        ),
        migrations.DeleteModel(
            name='WeeklyMission',
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['couple', 'period', 'start'], name='petcare_mis_couple__7a4cd5_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['next_fire'], name='petcare_rem_next_fi_4d189f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reminderrule',
            unique_together={('couple', 'hour', 'minute')},
        ),
        migrations.AddIndex(
            model_name='rewardbox',
            index=models.Index(fields=['couple', 'opened_at'], name='petcare_rew_couple__49223b_idx'),
        ),
    ]
