# Generated by Django 5.2.3 on 2025-06-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0002_mission_petmessage_reminder_reminderrule_rewardbox_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('kinza', 'Kinza'), ('kinba', 'Kinba'), ('kinmi', 'Kinmi')], default='kinza', max_length=20),
        ),
    ]
