# Generated by Django 5.2.3 on 2025-06-30 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0004_dicepocket'),
        ('users', '0003_couple_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='kind',
            field=models.CharField(choices=[('cook', 'Cook'), ('photo', 'Photo'), ('compliment', 'Compliment'), ('ai', 'AI Bonus'), ('feed', 'Feed')], max_length=12),
        ),
        migrations.CreateModel(
            name='PetFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fed_at', models.DateTimeField(auto_now_add=True)),
                ('food_type', models.CharField(default='snack', max_length=50)),
                ('amount', models.PositiveIntegerField(default=1)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_feeds', to='users.couple')),
            ],
            options={
                'ordering': ['-fed_at'],
                'indexes': [models.Index(fields=['couple', 'fed_at'], name='idx_petfeed_cpl')],
            },
        ),
    ]
