# Generated by Django 5.2.3 on 2025-07-25 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0005_alter_activity_kind_petfeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='nickname',
            field=models.CharField(default='Kinny', max_length=30),
        ),
    ]
