# Generated by Django 5.2.3 on 2025-08-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0006_alter_pet_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='period',
            field=models.CharField(choices=[('D', 'Daily'), ('W', 'Roundly'), ('C', 'Custom')], default='W', max_length=1),
        ),
        migrations.AlterField(
            model_name='petmessage',
            name='type',
            field=models.CharField(choices=[('tips', 'Tip'), ('summary', 'Roundly Summary'), ('recommend', 'Menu Recommend')], default='tips', max_length=12),
        ),
    ]
