# Generated by Django 5.2.3 on 2025-08-23 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petcare", "0006_alter_pet_nickname"),
        ("users", "0003_couple_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PetMessageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state_code",
                    models.CharField(
                        db_index=True,
                        help_text="状态代码 (state1, state2, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "message_template",
                    models.TextField(help_text="消息模板，支持变量如 {{recipe.name}}"),
                ),
                (
                    "weight",
                    models.IntegerField(default=1, help_text="随机选择时的权重"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="是否启用此模板"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Pet Message Template",
                "verbose_name_plural": "Pet Message Templates",
                "ordering": ["state_code", "weight"],
                "indexes": [
                    models.Index(
                        fields=["state_code", "is_active"], name="idx_pet_msg_tpl"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserPetMessageState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_states",
                    models.JSONField(
                        default=list,
                        help_text="当前激活的状态列表 ['state1', 'state3']",
                    ),
                ),
                (
                    "available_messages",
                    models.JSONField(default=list, help_text="当前可用的消息列表"),
                ),
                (
                    "new_states_since_last_check",
                    models.JSONField(default=list, help_text="用于短信通知的新增状态"),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "couple",
                    models.ForeignKey(
                        help_text="方便按couple查询",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_message_states",
                        to="users.couple",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pet_message_state",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Pet Message State",
                "verbose_name_plural": "User Pet Message States",
                "indexes": [
                    models.Index(
                        fields=["couple", "last_updated"], name="idx_user_pet_msg"
                    ),
                    models.Index(fields=["user"], name="idx_user_pet_msg_user"),
                ],
            },
        ),
    ]
