# Generated by Django 5.2.3 on 2025-08-25 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petcare", "0007_alter_mission_period_alter_petmessage_type"),
        ("petcare", "0007_petmessagetemplate_userpetmessagestate"),
    ]

    operations = []
