# Generated by Django 5.2.3 on 2025-08-28 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0008_merge_20250825_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpetmessagestate',
            name='new_states_since_last_check',
        ),
    ]
