# Generated by Django 5.2.3 on 2025-08-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petcare", "0009_remove_userpetmessagestate_new_states_since_last_check"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpetmessagestate",
            name="available_messages",
            field=models.JSONField(
                default=dict,
                help_text="按状态分组的消息 {'state1': ['msg1', 'msg2'], 'state3': ['msg3']}",
            ),
        ),
    ]
