# Generated by Django 5.2.5 on 2025-09-02 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0010_alter_userpetmessagestate_available_messages'),
        ('users', '0003_couple_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(choices=[('apple', '🍎 Apple'), ('banana', '🍌 Banana'), ('orange', '🍊 Orange'), ('strawberry', '🍓 Strawberry'), ('grapes', '🍇 Grapes'), ('watermelon', '🍉 Watermelon'), ('pineapple', '🍍 Pineapple'), ('cherry', '🍒 Cherry')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('last_harvest', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_inventory', to='users.couple')),
            ],
            options={
                'verbose_name': 'Food Inventory',
                'verbose_name_plural': 'Food Inventories',
                'indexes': [models.Index(fields=['couple', 'food_type'], name='petcare_foo_couple__55af2c_idx')],
                'unique_together': {('couple', 'food_type')},
            },
        ),
    ]
