# Generated by Django 5.2.5 on 2025-09-02 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0011_foodinventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='kind',
            field=models.CharField(choices=[('cook', 'Cook'), ('photo', 'Photo'), ('compliment', 'Compliment'), ('ai', 'AI Bonus'), ('feed', 'Feed'), ('game', 'Game')], max_length=12),
        ),
    ]
