# Generated by Django 5.2.5 on 2025-09-03 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0012_alter_activity_kind'),
        ('users', '0003_couple_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='foodinventory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='foodinventory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_inventory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='foodinventory',
            name='couple',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_inventory', to='users.couple'),
        ),
        migrations.AddIndex(
            model_name='foodinventory',
            index=models.Index(fields=['user', 'food_type'], name='petcare_foo_user_id_de46c4_idx'),
        ),
    ]
