# Generated by Django 5.2.5 on 2025-09-03 04:22

from django.db import migrations


def migrate_couple_inventory_to_users(apps, schema_editor):
    """将couple的食物库存迁移到两个用户的个人库存"""
    FoodInventory = apps.get_model('petcare', 'FoodInventory')
    
    # 获取所有基于couple的库存记录
    for inventory in FoodInventory.objects.filter(couple__isnull=False, user__isnull=True):
        # 为couple中的每个用户创建相同的库存记录
        for user in inventory.couple.members.all():
            FoodInventory.objects.create(
                user=user,
                food_type=inventory.food_type,
                quantity=inventory.quantity,
                last_harvest=inventory.last_harvest
            )
        # 删除原来的couple记录
        inventory.delete()


def reverse_migration(apps, schema_editor):
    """回滚：将用户库存合并回couple库存"""
    FoodInventory = apps.get_model('petcare', 'FoodInventory')
    
    # 这个回滚比较复杂，简单处理：删除所有用户库存
    FoodInventory.objects.filter(user__isnull=False).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0013_alter_foodinventory_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_couple_inventory_to_users, reverse_migration),
    ]
