# Generated by Django 5.2.5 on 2025-09-03 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0014_auto_20250903_0022'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='foodinventory',
            name='petcare_foo_couple__55af2c_idx',
        ),
        migrations.AlterUniqueTogether(
            name='foodinventory',
            unique_together={('user', 'food_type')},
        ),
        migrations.AlterField(
            model_name='foodinventory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_inventory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='foodinventory',
            name='couple',
        ),
    ]
