# Generated by Django 5.2.3 on 2025-09-03 22:27

import petcare.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0015_remove_foodinventory_petcare_foo_couple__55af2c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petstatus',
            name='last_tick',
            field=models.DateField(default=petcare.models.get_current_date),
        ),
    ]
