# Generated by Django 5.2.3 on 2025-06-15 22:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
        ('users', '0003_couple_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('content', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['posted_at'],
            },
        ),
        migrations.CreateModel(
            name='CookingDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='diary_images/')),
                ('ai_comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_locked', models.BooleanField(default=True)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('suggested_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
                ('feedback', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'ordering': ['-suggested_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='ingredientinrecipe',
            options={'ordering': ['recipe__name', 'ingredient__name']},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='ingredient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredientinrecipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredientinrecipe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='recipeingredienttask',
            name='couple',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_tasks', to='users.couple'),
        ),
        migrations.AddField(
            model_name='recipeingredienttask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='recipeingredienttask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='default_picture',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='default_picture',
            field=models.ImageField(blank=True, upload_to='ingredients/'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='quantity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='dish_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(help_text='烹饪步骤'),
        ),
        migrations.AlterField(
            model_name='recipeingredienttask',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='recipes.recipe'),
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredienttask',
            unique_together={('recipe', 'ingredient', 'couple')},
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['name'], name='idx_ing_name'),
        ),
        migrations.AddIndex(
            model_name='ingredientinrecipe',
            index=models.Index(fields=['recipe', 'ingredient'], name='idx_ing_in_rec'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['name'], name='idx_recipe_name'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['cuisine', 'dish_type'], name='idx_recipe_cui_type'),
        ),
        migrations.AddIndex(
            model_name='recipeingredienttask',
            index=models.Index(fields=['recipe', 'ingredient'], name='idx_task_ing'),
        ),
        migrations.AddIndex(
            model_name='recipeingredienttask',
            index=models.Index(fields=['couple', 'is_verified'], name='idx_task_cpl_ver'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cookingdiary',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cookingdiary',
            name='couple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to='users.couple'),
        ),
        migrations.AddField(
            model_name='cookingdiary',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='comment',
            name='diary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='recipes.cookingdiary'),
        ),
        migrations.AddField(
            model_name='familyrecipe',
            name='couple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_recipes', to='users.couple'),
        ),
        migrations.AddField(
            model_name='familyrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='recipesuggestion',
            name='couple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='users.couple'),
        ),
        migrations.AddField(
            model_name='recipesuggestion',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
        migrations.AddIndex(
            model_name='cookingdiary',
            index=models.Index(fields=['couple', 'created_at'], name='idx_diary_cpl'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['diary', 'posted_at'], name='idx_comment'),
        ),
        migrations.AddIndex(
            model_name='familyrecipe',
            index=models.Index(fields=['couple', 'is_locked'], name='idx_fr_cpl_lock'),
        ),
        migrations.AlterUniqueTogether(
            name='familyrecipe',
            unique_together={('couple', 'recipe')},
        ),
        migrations.AddIndex(
            model_name='recipesuggestion',
            index=models.Index(fields=['couple', 'used'], name='idx_suggest'),
        ),
    ]
