# Generated by Django 5.2.3 on 2025-06-18 21:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_comment_cookingdiary_familyrecipe_recipesuggestion_and_more'),
        ('users', '0003_couple_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CookingDiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('ai_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ai_feedback', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CookingDiaryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('image', models.ImageField(upload_to='diary_images/')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_locked', models.BooleanField(default=True)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.RemoveIndex(
            model_name='cookingdiary',
            name='idx_diary_cpl',
        ),
        migrations.RemoveField(
            model_name='cookingdiary',
            name='ai_comment',
        ),
        migrations.RemoveField(
            model_name='cookingdiary',
            name='author',
        ),
        migrations.RemoveField(
            model_name='cookingdiary',
            name='content',
        ),
        migrations.RemoveField(
            model_name='cookingdiary',
            name='image',
        ),
        migrations.AddField(
            model_name='cookingdiary',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='AI 综合评语', null=True),
        ),
        migrations.AddField(
            model_name='cookingdiary',
            name='turn',
            field=models.PositiveIntegerField(default=1, help_text='第几回合'),
        ),
        migrations.AddField(
            model_name='cookingdiary',
            name='winner',
            field=models.CharField(blank=True, choices=[('user1', 'User1'), ('user2', 'User2'), ('draw', 'Draw')], help_text='AI 评选结果', max_length=10),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='default_picture',
            field=models.ImageField(blank=True, null=True, upload_to='ingredients/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='default_picture',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/'),
        ),
        migrations.AddIndex(
            model_name='cookingdiary',
            index=models.Index(fields=['couple', 'turn'], name='idx_diary_round'),
        ),
        migrations.AddField(
            model_name='cookingdiaryentry',
            name='diary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='recipes.cookingdiary'),
        ),
        migrations.AddField(
            model_name='cookingdiaryentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cookingdiaryimage',
            name='diary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='recipes.cookingdiary'),
        ),
        migrations.AddField(
            model_name='cookingdiaryimage',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cookingdiaryentry',
            name='selected_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='recipes.cookingdiaryimage'),
        ),
        migrations.AddField(
            model_name='familymenu',
            name='couple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='users.couple'),
        ),
        migrations.AddField(
            model_name='menu',
            name='recipes',
            field=models.ManyToManyField(related_name='menus', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='familymenu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_menus', to='recipes.menu'),
        ),
        migrations.AddIndex(
            model_name='cookingdiaryentry',
            index=models.Index(fields=['diary', 'user'], name='idx_entry_diary_user'),
        ),
        migrations.AlterUniqueTogether(
            name='cookingdiaryentry',
            unique_together={('diary', 'user')},
        ),
        migrations.AddIndex(
            model_name='familymenu',
            index=models.Index(fields=['couple', 'is_locked'], name='idx_fm_cpl_lock'),
        ),
        migrations.AlterUniqueTogether(
            name='familymenu',
            unique_together={('couple', 'menu')},
        ),
    ]
