# Generated by Django 5.2.3 on 2025-06-21 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_cookingdiaryentry_cookingdiaryimage_familymenu_menu_and_more'),
        ('users', '0003_couple_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientPhotoProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('image', models.ImageField(upload_to='ingredient_proofs/')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proof', to='recipes.recipeingredienttask')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='idx_proof_created')],
            },
        ),
        migrations.CreateModel(
            name='WeeklyBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('week', models.DateField(help_text='自然周周一')),
                ('rerolled', models.BooleanField(default=False)),
                ('rerolled_at', models.DateTimeField(blank=True, null=True)),
                ('active_recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.recipe')),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='users.couple')),
            ],
            options={
                'indexes': [models.Index(fields=['couple', 'week'], name='idx_bracket_week')],
                'unique_together': {('couple', 'week')},
            },
        ),
    ]
