# Generated by Django 5.2.3 on 2025-06-23 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_ingredientphotoproof_weeklybracket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookingdiary',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cookingdiary',
            name='turn',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cookingdiary',
            name='winner',
            field=models.CharField(blank=True, choices=[('user1', 'User1'), ('user2', 'User2'), ('draw', 'Draw')], max_length=10),
        ),
        migrations.AlterField(
            model_name='familyrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_recipes', to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(help_text='Cooking steps'),
        ),
        migrations.AlterField(
            model_name='weeklybracket',
            name='week',
            field=models.DateField(help_text='Monday of the week'),
        ),
    ]
