# Generated by Django 5.2.3 on 2025-07-03 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_alter_cookingdiary_ai_summary_and_more"),
    ]

    operations = [
        # idx_diary_round covers cookingdiary.couple, so it has to go before the
        # field does. PostgreSQL drops dependent indexes together with the
        # column, which is why this migration applied cleanly there; SQLite
        # rebuilds the table from migration state and fails with
        # FieldDoesNotExist, breaking `migrate` on a fresh checkout using the
        # documented dev backend. CookingDiary is deleted further down anyway,
        # so the end state is unchanged and migrated databases are unaffected.
        migrations.RemoveIndex(
            model_name="cookingdiary",
            name="idx_diary_round",
        ),
        migrations.RemoveIndex(
            model_name="cookingdiaryentry",
            name="idx_entry_diary_user",
        ),
        migrations.AlterUniqueTogether(
            name="cookingdiaryentry",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="cookingdiary",
            name="couple",
        ),
        migrations.RemoveField(
            model_name="cookingdiary",
            name="recipe",
        ),
        migrations.RemoveField(
            model_name="cookingdiaryentry",
            name="diary",
        ),
        migrations.RemoveField(
            model_name="cookingdiaryimage",
            name="diary",
        ),
        migrations.RemoveField(
            model_name="cookingdiaryentry",
            name="selected_image",
        ),
        migrations.RemoveField(
            model_name="cookingdiaryentry",
            name="user",
        ),
        migrations.RemoveField(
            model_name="cookingdiaryimage",
            name="uploader",
        ),
        migrations.AlterField(
            model_name="ingredientphotoproof",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proofs",
                to="recipes.recipeingredienttask",
            ),
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="CookingDiary",
        ),
        migrations.DeleteModel(
            name="CookingDiaryEntry",
        ),
        migrations.DeleteModel(
            name="CookingDiaryImage",
        ),
    ]
