# Generated by Django 5.2.3 on 2025-07-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_remove_cookingdiary_couple_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preparation',
            field=models.TextField(blank=True, help_text='Optional preparation notes (marinate, soak, etc.)'),
        ),
    ]
