# Generated by Django 5.2.3 on 2025-07-18 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_preparation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='default_picture',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='slug',
        ),
    ]
