# Generated by Django 5.2.5 on 2025-08-25 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_recipe_default_picture_recipe_slug'),
        ('users', '0003_couple_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipeingredienttask',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='recipeingredienttask',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The specific user who needs to complete this task', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredienttask',
            unique_together={('recipe', 'ingredient', 'user')},
        ),
        migrations.AddIndex(
            model_name='recipeingredienttask',
            index=models.Index(fields=['user', 'is_verified'], name='idx_task_user_ver'),
        ),
    ]
