# Generated by Django 5.2.3 on 2025-08-20 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_recipe_default_picture_recipe_slug'),
        ('users', '0003_couple_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeeklyBracket',
            new_name='RoundBracket',
        ),
    ]
