# Generated by Django 5.2.5 on 2025-08-25 04:17

from django.db import migrations


def populate_user_field(apps, schema_editor):
    """
    backfill the user field on existing RecipeIngredientTask rows
    如果couple有用户，就将第一个用户分配给现有任务
    """
    RecipeIngredientTask = apps.get_model('recipes', 'RecipeIngredientTask')
    
    for task in RecipeIngredientTask.objects.filter(user__isnull=True):
        if task.couple and task.couple.members.exists():
            # 将第一个用户分配给现有任务
            first_user = task.couple.members.first()
            task.user = first_user
            task.save(update_fields=['user'])


def reverse_populate_user_field(apps, schema_editor):
    """
    回滚操作：清空user字段
    """
    RecipeIngredientTask = apps.get_model('recipes', 'RecipeIngredientTask')
    RecipeIngredientTask.objects.update(user=None)


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_recipeingredienttask_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_user_field, reverse_populate_user_field),
    ]
