# Generated by Django 5.2.3 on 2025-08-20 09:49
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_rename_weeklybracket_roundbracket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roundbracket',
            old_name='week',
            new_name='round',
        ),
    ]