# Generated by Django 5.2.3 on 2025-08-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_rename_week_to_round'),
        ('users', '0003_couple_name'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='roundbracket',
            name='idx_bracket_week',
        ),
        migrations.AlterField(
            model_name='roundbracket',
            name='round',
            field=models.DateField(help_text='First day of the round'),
        ),
        migrations.AddIndex(
            model_name='roundbracket',
            index=models.Index(fields=['couple', 'round'], name='idx_bracket_round'),
        ),
    ]
