# Generated by Django 5.2.3 on 2025-08-25 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20250825_0417'),
        ('recipes', '0012_remove_roundbracket_idx_bracket_week_and_more'),
    ]

    operations = [
    ]
