# Generated by Django 5.2.3 on 2025-09-06 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0013_merge_20250825_0113"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientphotoproof",
            name="task",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proof",
                to="recipes.recipeingredienttask",
            ),
        ),
    ]
