# Generated by Django 5.2.5 on 2025-10-04 07:15

from django.db import migrations


class Migration(migrations.Migration):
    """
    🧹 Clean up: Remove old SystemConfig model from recipes app
    SystemConfig has been moved to the dedicated 'system' app for better separation of concerns
    """

    dependencies = [
        ('recipes', '0014_alter_ingredientphotoproof_task'),
    ]

    operations = [
        # Delete the old SystemConfig table from recipes app
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS recipes_systemconfig;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
