# Generated by Django 5.2.3 on 2025-10-12 03:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique identifier: navigation, ai, recipe, pet', max_length=50, unique=True, verbose_name='Category Name')),
                ('display_name', models.CharField(max_length=100, verbose_name='Display Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, max_length=10, verbose_name='Icon')),
                ('color', models.CharField(default='#6c757d', max_length=7, verbose_name='Color Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event Category',
                'verbose_name_plural': 'Event Categories',
                'db_table': 'analytics_event_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Event Name')),
                ('display_name', models.CharField(max_length=150, verbose_name='Display Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_important', models.BooleanField(default=False, verbose_name='Important Event')),
                ('is_active', models.BooleanField(default=True, verbose_name='Enable Tracking')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_types', to='analytics.eventcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Event Type',
                'verbose_name_plural': 'Event Types',
                'db_table': 'analytics_event_type',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EventAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20, verbose_name='Period')),
                ('period_start', models.DateTimeField(db_index=True, verbose_name='Period Start')),
                ('period_end', models.DateTimeField(verbose_name='Period End')),
                ('total_count', models.IntegerField(default=0, verbose_name='Total Count')),
                ('unique_users', models.IntegerField(default=0, verbose_name='Unique Users')),
                ('success_count', models.IntegerField(default=0, verbose_name='Success Count')),
                ('failed_count', models.IntegerField(default=0, verbose_name='Failed Count')),
                ('avg_duration_ms', models.FloatField(blank=True, null=True, verbose_name='Avg Duration (ms)')),
                ('aggregated_data', models.JSONField(blank=True, default=dict, verbose_name='Aggregated Data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregates', to='analytics.eventtype', verbose_name='Event Type')),
            ],
            options={
                'verbose_name': 'Event Statistics',
                'verbose_name_plural': 'Event Statistics',
                'db_table': 'analytics_event_aggregate',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Session ID')),
                ('resource_type', models.CharField(blank=True, max_length=50, verbose_name='Resource Type')),
                ('resource_id', models.CharField(blank=True, max_length=100, verbose_name='Resource ID')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('duration_ms', models.IntegerField(blank=True, null=True, verbose_name='Duration (ms)')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='success', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics.eventtype', verbose_name='Event Type')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_events', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Behavior Event',
                'verbose_name_plural': 'User Behavior Events',
                'db_table': 'analytics_user_event',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Session ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Started At')),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Activity At')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Ended At')),
                ('event_count', models.IntegerField(default=0, verbose_name='Event Count')),
                ('duration_seconds', models.IntegerField(blank=True, null=True, verbose_name='Duration (seconds)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('device_type', models.CharField(blank=True, max_length=20, verbose_name='Device Type')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'db_table': 'analytics_user_session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='eventtype',
            index=models.Index(fields=['category', 'is_active'], name='analytics_e_categor_a0d5ca_idx'),
        ),
        migrations.AddIndex(
            model_name='eventtype',
            index=models.Index(fields=['is_important'], name='analytics_e_is_impo_6c637b_idx'),
        ),
        migrations.AddIndex(
            model_name='eventaggregate',
            index=models.Index(fields=['event_type', 'period', '-period_start'], name='analytics_e_event_t_449cb1_idx'),
        ),
        migrations.AddIndex(
            model_name='eventaggregate',
            index=models.Index(fields=['period', '-period_start'], name='analytics_e_period_46cc74_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventaggregate',
            unique_together={('event_type', 'period', 'period_start')},
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['user', '-timestamp'], name='analytics_u_user_id_b43228_idx'),
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['event_type', '-timestamp'], name='analytics_u_event_t_b25263_idx'),
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['session_id', '-timestamp'], name='analytics_u_session_0dbf48_idx'),
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['resource_type', 'resource_id'], name='analytics_u_resourc_a5fe18_idx'),
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['status'], name='analytics_u_status_bb7125_idx'),
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['-timestamp'], name='analytics_u_timesta_deae40_idx'),
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['event_type', 'user', '-timestamp'], name='analytics_u_event_t_8d8c62_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', '-started_at'], name='analytics_u_user_id_3d7ba7_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_id'], name='analytics_u_session_9b208e_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['-started_at'], name='analytics_u_started_6d4dbf_idx'),
        ),
    ]
