# Generated by Django 5.2.3 on 2025-10-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='resource_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Resource ID'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='resource_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Resource Type'),
        ),
    ]
