# Generated by Django 5.2.3 on 2025-10-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_userevent_resource_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Error Message'),
        ),
    ]
